// packages/workshop/app/components/image-preview.tsx
import { useFileObjectUrl } from "~/lib/hooks/file-object-url";

export interface ImagePreviewProps {
  directoryHandle: FileSystemDirectoryHandle;
  path: string | undefined;
}

export const ImagePreview = ({ directoryHandle, path }: ImagePreviewProps) => {
  const [imageUrl, error] = useFileObjectUrl(directoryHandle, path);

  return (
    <div style={{ padding: "1rem" }}>
      {error ? (
        <>
          Unable to load {path}: {error}
        </>
      ) : imageUrl ? (
        <img src={imageUrl} style={{ maxWidth: "100%" }} alt={path} />
      ) : (
        "Loading"
      )}
    </div>
  );
};

// packages/workshop/src/ImagePreview.svelte
<script lang="ts">
  import { resolveFileFromPath } from "./resolveFile";

  interface Props {
    directoryHandle: FileSystemDirectoryHandle;
    path: string | undefined;
  }

  const { directoryHandle, path }: Props = $props();

  const imageUrlPromise = $derived(
    (async () => {
      if (!path) return undefined;
      const fileHandle = await resolveFileFromPath(directoryHandle, path);
      const file = await fileHandle.getFile();
      return URL.createObjectURL(file);
    })(),
  );
</script>

<div style="padding: 1rem">
  {#await imageUrlPromise}
    Loading
  {:then url}
    {#if url}
      <img src={url} style="max-width: 100%" alt={path} />
    {:else}
      Not specified
    {/if}
  {:catch e}
    Unable to load {path}: {e}
  {/await}
</div>
